onlyBuiltDependencies:
  - core-js
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  tmp@<=0.2.3: '>=0.2.4'
